src/Entity/Vaccine.php
<?php

namespace App\Entity;

use App\Repository\VaccineRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VaccineRepository::class)]
class Vaccine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNext = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateCurrent = null;

    #[ORM\ManyToOne]
    private ?Animal $Animal = null;

    #[ORM\ManyToOne(inversedBy: 'vaccines')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Animal $animal = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateNext(): ?\DateTimeInterface
    {
        return $this->dateNext;
    }

    public function setDateNext(?\DateTimeInterface $dateNext): self
    {
        $this->dateNext = $dateNext;

        return $this;
    }

    public function getDateCurrent(): ?\DateTimeInterface
    {
        return $this->dateCurrent;
    }

    public function setDateCurrent(?\DateTimeInterface $dateCurrent): self
    {
        $this->dateCurrent = $dateCurrent;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->Animal;
    }

    public function setAnimal(?Animal $Animal): self
    {
        $this->Animal = $Animal;

        return $this;
    }
}

src/Entity/Veto.php
<?php

namespace App\Entity;

use App\Repository\VetoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VetoRepository::class)]
class Veto extends User
{
    #[ORM\OneToMany(mappedBy: 'veto', targetEntity: Appointment::class)]
    private Collection $appointments;

    #[ORM\OneToOne(inversedBy: 'veto', cascade: ['persist', 'remove'])]
    private ?Agenda $agenda = null;

    public function __construct()
    {
        parent::__construct();
        $this->appointments = new ArrayCollection();
    }

    /**
     * @return Collection<int, Appointment>
     */
    public function getAppointments(): Collection
    {
        return $this->appointments;
    }

    public function addAppointment(Appointment $appointment): self
    {
        if (!$this->appointments->contains($appointment)) {
            $this->appointments->add($appointment);
            $appointment->setVeto($this);
        }

        return $this;
    }

    public function removeAppointment(Appointment $appointment): self
    {
        if ($this->appointments->removeElement($appointment)) {
            // set the owning side to null (unless already changed)
            if ($appointment->getVeto() === $this) {
                $appointment->setVeto(null);
            }
        }

        return $this;
    }

    public function getAgenda(): ?Agenda
    {
        return $this->agenda;
    }

    public function setAgenda(?Agenda $agenda): self
    {
        $this->agenda = $agenda;

        return $this;
    }

    public function getDisplayName(): string
    {
        return sprintf("Dr %s $this->firstName", strtoupper($this->lastName));
    }
}

src/Controller/VaccineController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Entity\Vaccine;
use App\Entity\Veto;
use App\Form\VaccineFormType;
use App\Repository\VaccineRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VaccineController extends AbstractController
{
    #[Route('/vaccine/add/{id}',
        name: 'app_vaccine_add',
        requirements: ['id' => "\d+"])]
    public function add(VaccineRepository $repository, Animal $animal, Request $request): Response
    {
        $createForm = $this->createForm(VaccineFormType::class);
        $createForm->handleRequest($request);

        $user = $this->getUser();
        if (!$user instanceof Veto) {
            throw $this->createAccessDeniedException();
        }

        if ($createForm->isSubmitted() && $createForm->isValid()) {
            /** @var $vaccine Vaccine */
            $vaccine = $createForm->getData();
            $vaccine->setAnimal($animal);
            $repository->save($vaccine, true);
        }

        return $this->renderForm('vaccine/index.html.twig', [
            'create_form' => $createForm,
            'animal' => $animal,
            'client' => $animal->getClientAnimal(),
        ]);
    }

    #[Route('/vaccine/add/{id}',
        name: 'app_vaccine_remove',
        requirements: ['id' => "\d+"])]
    public function remove(VaccineRepository $repository, Vaccine $vaccine): Response
    {
        $user = $this->getUser();
        if (!$user instanceof Veto) {
            throw $this->createAccessDeniedException();
        }

        $animalId = $vaccine->getAnimal()->getId();
        $repository->remove($vaccine, true);
        return $this->redirectToRoute('app_animal', ['id' => $animalId]);
    }
}

templates/vaccine/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

<input type="submit" class="btn btn-primary" value="{{ label_submit }}">
{{ form_end(form) }}

templates/vaccine/_vaccines.html.twig
<main>
    <div class="main-content">
        <div class="main-content__home">
            <h1 class="title">Mes Vaccins</h1>
            <p style="text-align: center">
            <a class="btn btn-primary" href="{{ path('app_vaccine_create') }}" role="button"> Ajouter un vaccin</a>
            </p>
            <ul class="list_animal">
                {% for vaccine in vaccines  %}
                <div class="list_animal_item">
                    <div class="animal_part">
                        <p class="animal_name">{{vaccine.name}}</p>
                        <p class="animal-type">{{vaccine.dateCurrent |format_date}}</p>
                        <p class="animal-type">{{vaccine.dateNext |format_date}}</p>
                    </div>
                    <textarea class="form-control"> </textarea>
                    <div class="animal_part">
                        <p class="animal_button"><a class="btn btn-success" href="{{ path('app_animal_update', {id: animal.id}) }}" role="button"> Modifier cet animal</a> </p>
                        <p class="animal_button"><a class="btn btn-danger" href="{{ path('app_animal_delete', {id: animal.id}) }}" role="button"> Supprimer cet animal</a></p>
                        <p class="animal_button"><a class="btn btn-success" href="{{ path('app_record_animal', {id: animal.id}) }}" role="button"> Accéder aux derniers récap !</a></p>
                    </div>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</main>

templates/vaccine/create.twig
{% extends 'base.html.twig' %}

{% block title %}
    Création d'un nouveau vaccin
{% endblock %}

{% block main %}
    <div class="main-content">
        <h1>Création d'un nouveau vaccin</h1>

        {{ include('vaccine/_form.html.twig', {label_submit: "créer", with_context: false, form: form}) }}
    </div>

{% endblock %}

templates/vaccine/delete.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ "Suppression du vaccin #{vaccine.name}" }}
{% endblock %}

{% block main %}
    <div class="main-content">
        <h1>{{ "Suppression du vaccin #{vaccine.name}" }}</h1>
        <p> êtes vous sur de vouloir supprimer ce vaccin ?</p>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/vaccine/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Take'A'Vet - Vaccins{% endblock %}

{% block main %}
    <div class="main-content">
        <h1 class="text-center">Ajouter un vaccin pour {{ animal.displayName }}</h1>

        <div class="d-flex gap-5 col-row-responsive">
            <div class="flex-grow-1">
                {{ form_start(create_form) }}
                {{ form_widget(create_form) }}
                <input type="submit" class="btn btn-primary" value="Ajouter">
                {{ form_end(create_form) }}
            </div>
            {{ include('_animal_card.html.twig', {animal: animal, client: client}) }}
        </div>
    </div>
{% endblock %}

templates/vaccine/update.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ "Modification du vaccin #{vaccine.name}" }}
{% endblock %}

{% block main %}
    <div class="main-content">
        <h1>{{  "Modification du vaccin #{vaccine.name}"}}</h1>
        {{ include('vaccine/_form.html.twig', {
            label_submit: "modifier",
            with_context: false,
            form: form
        })
        }}
    </div>
{% endblock %}